jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UseDotNet@2
    inputs:
      version: '2.x'
  - task: UseDotNet@2
    inputs:
      version: '3.x'
  - script: build -target BuildServer
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      MYGET_KEY: $(MYGET_KEY)
- job: Linux
  pool:
    vmImage: 'ubuntu 16.04'
  steps:
  - script: pwsh ./build.ps1 -target BuildServer
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
- job: Mac
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: pwsh ./build.ps1 -target BuildServer
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)